circumvent = এড়িয়ে যাওয়া 
determine = নির্ধারিত
truncated = কাটা
dedication = উৎসর্গ
imperative = অপরিহার্য
antithesis = বিরোধী
prior = পূর্বে
symmetry = ভারসাম্য
overlap = কোনোকিছুকে অংশত ঢেকে রাখা
pedagogy = শিক্ষাবিদ্যা
regardless = নির্বিশেষে
asap = যত তাড়াতাড়ি সম্ভব
explanatory = ব্যাখ্যামূলক
caters = পূরণ করে
ranging = রেঞ্জিং 
Commentary = ভাষ্য
normative = আদর্শিক
autonomy = স্বায়ত্তশাসন
cluster = গুচ্ছ
hierarchy = শ্রেণিবিন্যাস
interpret = ব্যাখ্যা করা
interpret = meaning , explanation 
nonetheless = তবুও
Hence = তাই
suﬃces = সাফল্য
orchestrating = decorate , সাজসজ্জা
consecutively = ধারাবাহিকভাবে
tend = ঝোঁক 
fetched = আনা হয়েছে
retrieve = উদ্ধার করা
respectively = যথাক্রমে
unary = একক, একটিমাত্র
symphonies = ঐকতান, সম্মিলিত সুর, বাদ্যযন্ত্রের সমবেত ধ্বনি , মিল
assume = অনুমান
jargon = পরিভাষা , অর্থহীন ভাষা
annotate = টীকা
consecutive = ক্রমাগত
capable = সক্ষম
cater = খাদ্য সরবরাহ করা , খাবারদাবারের যোগান দেওয়া;
extent = পরিমাণ
integrity = সততা
skim = সরে যাওয়া
realm = রাজ্য
